# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0002_auto_20170225_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='_render_cache',
            field=models.TextField(blank=True, null=True),
        ),
    ]
