# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0002_unitmodel_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='weight',
            field=models.IntegerField(default=-1),
        ),
    ]
