# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0003_pagecontent__render_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_page', to='markdown.Page'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, to='markdown.Page'),
        ),
    ]
