# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown', '0003_pagecontent_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
